import { db, teachersTable, coursesTable, examsTable, blogPostsTable, testimonialsTable } from "@workspace/db";
import { logger } from "./logger";

export async function seedIfEmpty() {
  const teachers = await db.select().from(teachersTable).limit(1);
  if (teachers.length > 0) return;

  logger.info("Seeding database with initial data...");

  await db.insert(teachersTable).values([
    {
      name: "Thầy Nguyễn Minh Tuấn",
      avatar: "https://api.dicebear.com/7.x/initials/svg?seed=NMT&backgroundColor=102A43&textColor=ffffff",
      specialization: "Toán HSA - Đại số & Giải tích",
      experienceYears: 12,
      studentsCount: 3200,
      bio: "Thầy Tuấn có 12 năm kinh nghiệm giảng dạy toán luyện thi HSA. Tốt nghiệp Đại học Bách Khoa Hà Nội, chuyên sâu về đại số và giải tích. Hơn 3.000 học sinh đã đạt điểm HSA trên 100 nhờ phương pháp giảng dạy hệ thống của thầy.",
      rating: 4.9,
    },
    {
      name: "Cô Trần Thị Lan Anh",
      avatar: "https://api.dicebear.com/7.x/initials/svg?seed=TLA&backgroundColor=E85A2A&textColor=ffffff",
      specialization: "Ngữ văn HSA - Đọc hiểu & Nghị luận",
      experienceYears: 9,
      studentsCount: 2100,
      bio: "Cô Lan Anh chuyên luyện thi phần Ngữ văn và Khoa học xã hội trong kỳ thi HSA. Với kinh nghiệm 9 năm, cô đã giúp hàng nghìn học sinh cải thiện điểm đọc hiểu từ 20% lên trên 80%.",
      rating: 4.8,
    },
    {
      name: "Thầy Phạm Đức Hùng",
      avatar: "https://api.dicebear.com/7.x/initials/svg?seed=PDH&backgroundColor=102A43&textColor=ffffff",
      specialization: "TSA - Tư duy Toán học & Phân tích",
      experienceYears: 7,
      studentsCount: 1800,
      bio: "Thầy Hùng là chuyên gia về kỳ thi TSA của Đại học Bách Khoa Hà Nội, đặc biệt phần tư duy toán học và suy luận logic. Học viên của thầy có tỷ lệ đạt trên 90 điểm TSA đạt 78%.",
      rating: 4.9,
    },
    {
      name: "Cô Lê Ngọc Phương",
      avatar: "https://api.dicebear.com/7.x/initials/svg?seed=LNP&backgroundColor=F7941D&textColor=ffffff",
      specialization: "Khoa học tự nhiên HSA",
      experienceYears: 8,
      studentsCount: 1500,
      bio: "Cô Phương có chuyên môn sâu về phần Khoa học tự nhiên trong kỳ thi HSA bao gồm Vật lý, Hóa học, Sinh học. Phương pháp học tập trực quan của cô giúp học sinh ghi nhớ kiến thức hiệu quả hơn 60%.",
      rating: 4.7,
    },
  ]);

  await db.insert(coursesTable).values([
    {
      title: "Toán HSA Nâng Cao - Đại Số & Giải Tích",
      teacherName: "Thầy Nguyễn Minh Tuấn",
      teacherAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=NMT&backgroundColor=102A43&textColor=ffffff",
      rating: 4.9,
      studentsCount: 1240,
      price: 899000,
      originalPrice: 1299000,
      category: "HSA",
      thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&q=80",
      level: "Nâng cao",
      lessonsCount: 48,
      durationHours: 36,
      description: "Khóa học toàn diện về Toán HSA, bao gồm Đại số, Giải tích, Hình học và Xác suất thống kê. Được thiết kế theo đúng cấu trúc đề thi HSA của ĐHQGHN.",
      whatYouLearn: [
        "Nắm vững toàn bộ kiến thức Đại số thi HSA",
        "Thành thạo các dạng bài Giải tích cơ bản",
        "Giải quyết nhanh bài Hình học phẳng và không gian",
        "Chiến lược làm bài thi hiệu quả trong 150 phút",
      ],
      curriculum: [
        { title: "Phần 1: Đại số cơ bản", lessons: ["Hàm số và đồ thị", "Phương trình và bất phương trình", "Dãy số"] },
        { title: "Phần 2: Giải tích", lessons: ["Giới hạn và liên tục", "Đạo hàm", "Tích phân"] },
        { title: "Phần 3: Hình học", lessons: ["Hình học phẳng", "Hình học không gian", "Tọa độ"] },
        { title: "Phần 4: Xác suất - Thống kê", lessons: ["Xác suất cơ bản", "Thống kê mô tả", "Phân phối xác suất"] },
      ],
    },
    {
      title: "Ngữ Văn HSA - Đọc Hiểu & Nghị Luận",
      teacherName: "Cô Trần Thị Lan Anh",
      teacherAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=TLA&backgroundColor=E85A2A&textColor=ffffff",
      rating: 4.8,
      studentsCount: 980,
      price: 749000,
      originalPrice: 999000,
      category: "HSA",
      thumbnail: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&q=80",
      level: "Trung bình",
      lessonsCount: 36,
      durationHours: 28,
      description: "Khóa học chuyên sâu phần Ngữ văn và Khoa học xã hội trong đề thi HSA. Rèn luyện kỹ năng đọc hiểu nhanh và viết nghị luận đạt điểm cao.",
      whatYouLearn: [
        "Kỹ thuật đọc hiểu văn bản nhanh và chính xác",
        "Cấu trúc bài nghị luận đạt điểm tối đa",
        "Mở rộng vốn từ chuyên ngành",
        "Phân tích và xử lý thông tin từ biểu đồ, số liệu",
      ],
      curriculum: [
        { title: "Phần 1: Đọc hiểu văn bản", lessons: ["Kỹ năng đọc nhanh", "Phân tích luận điểm", "Bài tập thực hành"] },
        { title: "Phần 2: Nghị luận xã hội", lessons: ["Cấu trúc bài viết", "Lập luận logic", "Ví dụ minh họa"] },
        { title: "Phần 3: Kiến thức xã hội", lessons: ["Lịch sử Việt Nam", "Địa lý", "GDCD"] },
      ],
    },
    {
      title: "TSA Full Course - Tư Duy Toàn Diện",
      teacherName: "Thầy Phạm Đức Hùng",
      teacherAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=PDH&backgroundColor=102A43&textColor=ffffff",
      rating: 4.9,
      studentsCount: 1560,
      price: 1199000,
      originalPrice: 1699000,
      category: "TSA",
      thumbnail: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&q=80",
      level: "Nâng cao",
      lessonsCount: 60,
      durationHours: 45,
      description: "Khóa học đầy đủ nhất về kỳ thi TSA của Đại học Bách Khoa Hà Nội. Bao gồm tư duy toán học, tư duy đọc hiểu và giải quyết vấn đề.",
      whatYouLearn: [
        "Tư duy toán học suy luận logic TSA",
        "Đọc hiểu và phân tích văn bản học thuật",
        "Giải quyết vấn đề theo phương pháp khoa học",
        "Chiến lược làm bài thi TSA trong 90 phút",
      ],
      curriculum: [
        { title: "Phần 1: Tư duy toán học", lessons: ["Logic & Suy luận", "Đại số & Hàm số", "Hình học tư duy"] },
        { title: "Phần 2: Tư duy đọc hiểu", lessons: ["Đọc hiểu học thuật", "Phân tích lập luận", "Suy luận từ dữ liệu"] },
        { title: "Phần 3: Giải quyết vấn đề", lessons: ["Phân tích tình huống", "Tìm giải pháp tối ưu", "Đánh giá phương án"] },
      ],
    },
    {
      title: "Khoa Học Tự Nhiên HSA - Vật Lý, Hóa, Sinh",
      teacherName: "Cô Lê Ngọc Phương",
      teacherAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=LNP&backgroundColor=F7941D&textColor=ffffff",
      rating: 4.7,
      studentsCount: 720,
      price: 849000,
      originalPrice: 1199000,
      category: "HSA",
      thumbnail: "https://images.unsplash.com/photo-1532094349884-543559059af7?w=600&q=80",
      level: "Trung bình",
      lessonsCount: 42,
      durationHours: 32,
      description: "Khóa học phần Khoa học tự nhiên trong đề thi HSA, bao gồm Vật lý, Hóa học và Sinh học. Phương pháp học trực quan, dễ nhớ.",
      whatYouLearn: [
        "Nắm vững các định luật Vật lý cơ bản",
        "Thành thạo phản ứng hóa học trong HSA",
        "Hiểu rõ cơ chế sinh học ở mức độ tế bào",
        "Kỹ thuật làm bài trắc nghiệm khoa học hiệu quả",
      ],
      curriculum: [
        { title: "Vật lý", lessons: ["Cơ học", "Điện từ học", "Quang học"] },
        { title: "Hóa học", lessons: ["Hóa đại cương", "Hóa hữu cơ", "Hóa vô cơ"] },
        { title: "Sinh học", lessons: ["Tế bào học", "Di truyền học", "Sinh thái học"] },
      ],
    },
    {
      title: "Toán TSA - Chuyên Sâu Đại Số Tư Duy",
      teacherName: "Thầy Phạm Đức Hùng",
      teacherAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=PDH&backgroundColor=102A43&textColor=ffffff",
      rating: 4.8,
      studentsCount: 890,
      price: 699000,
      originalPrice: null,
      category: "TSA",
      thumbnail: "https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=600&q=80",
      level: "Cơ bản",
      lessonsCount: 32,
      durationHours: 24,
      description: "Tập trung vào phần Toán tư duy trong TSA, rèn luyện khả năng suy luận logic và giải quyết bài toán phức hợp nhanh chóng.",
      whatYouLearn: [
        "Tư duy logic qua bài toán đại số",
        "Phân tích và giải quyết bài toán phức tạp",
        "Tốc độ làm bài trong điều kiện thi thật",
        "Kiểm soát thời gian thi hiệu quả",
      ],
      curriculum: [
        { title: "Tư duy logic", lessons: ["Suy luận diễn dịch", "Suy luận quy nạp", "Phân tích mệnh đề"] },
        { title: "Toán học ứng dụng", lessons: ["Hàm số", "Xác suất", "Tổ hợp"] },
      ],
    },
    {
      title: "Ôn Thi HSA Tổng Hợp - Luyện Đề Chuyên Sâu",
      teacherName: "Thầy Nguyễn Minh Tuấn",
      teacherAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=NMT&backgroundColor=102A43&textColor=ffffff",
      rating: 4.9,
      studentsCount: 2100,
      price: 1499000,
      originalPrice: 1999000,
      category: "HSA",
      thumbnail: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&q=80",
      level: "Nâng cao",
      lessonsCount: 72,
      durationHours: 54,
      description: "Khóa học luyện đề tổng hợp toàn bộ chương trình HSA. Giải chi tiết 200+ đề thi thật từ 2018-2024, bao gồm tất cả các môn.",
      whatYouLearn: [
        "Ôn luyện toàn diện tất cả các phần thi HSA",
        "Chiến lược phân bổ thời gian thi 150 phút",
        "Phân tích điểm mạnh yếu cá nhân",
        "Mô phỏng kỳ thi thật với 50 đề đầy đủ",
      ],
      curriculum: [
        { title: "Giai đoạn 1: Ôn tập nền tảng", lessons: ["Toán", "Ngữ văn", "Khoa học"] },
        { title: "Giai đoạn 2: Luyện đề", lessons: ["Đề 2020-2022", "Đề 2023-2024", "Đề dự đoán 2025"] },
        { title: "Giai đoạn 3: Thi thử", lessons: ["10 đề thi thử đầy đủ", "Phân tích kết quả", "Cải thiện điểm yếu"] },
      ],
    },
  ]);

  await db.insert(examsTable).values([
    {
      title: "HSA ĐHQGHN 2024 - Đề Chính Thức",
      type: "HSA",
      subject: "Tổng hợp",
      difficulty: "Khó",
      questionsCount: 120,
      durationMinutes: 150,
      attemptCount: 8420,
      isFree: true,
      year: 2024,
      description: "Đề thi HSA chính thức năm 2024 của ĐHQGHN. Bao gồm đầy đủ các phần: Tư duy định lượng, Tư duy định tính và Khoa học.",
      questions: [
        { id: 1, text: "Nếu f(x) = 2x² - 3x + 1, giá trị của f(2) là:", options: ["A. 3", "B. 5", "C. 7", "D. 9"], correctOptionIndex: 0, explanation: "f(2) = 2(4) - 3(2) + 1 = 8 - 6 + 1 = 3" },
        { id: 2, text: "Đạo hàm của hàm số y = x³ - 2x² + 5x - 1 tại x = 1 là:", options: ["A. 2", "B. 3", "C. 4", "D. 5"], correctOptionIndex: 2, explanation: "y' = 3x² - 4x + 5, tại x=1: y'(1) = 3 - 4 + 5 = 4" },
        { id: 3, text: "Phương trình 2x² - 5x + 2 = 0 có nghiệm là:", options: ["A. x = 2 hoặc x = 0.5", "B. x = 1 hoặc x = 2", "C. x = -2 hoặc x = -0.5", "D. Vô nghiệm"], correctOptionIndex: 0, explanation: "Δ = 25 - 16 = 9, x = (5±3)/4, x₁ = 2, x₂ = 0.5" },
      ],
    },
    {
      title: "TSA Bách Khoa 2024 - Đề Chính Thức",
      type: "TSA",
      subject: "Tổng hợp",
      difficulty: "Khó",
      questionsCount: 100,
      durationMinutes: 90,
      attemptCount: 5630,
      isFree: true,
      year: 2024,
      description: "Đề thi TSA chính thức năm 2024 của Đại học Bách Khoa Hà Nội. Bao gồm tư duy toán học, tư duy đọc hiểu và giải quyết vấn đề.",
      questions: [
        { id: 1, text: "Trong một dãy số 2, 6, 18, 54, ..., số hạng tiếp theo là:", options: ["A. 108", "B. 162", "C. 216", "D. 270"], correctOptionIndex: 1, explanation: "Đây là cấp số nhân với công bội q = 3. Số hạng tiếp theo = 54 × 3 = 162" },
        { id: 2, text: "Nếu một tập hợp có 5 phần tử, số tập con của nó là:", options: ["A. 25", "B. 32", "C. 10", "D. 64"], correctOptionIndex: 1, explanation: "Số tập con của tập n phần tử là 2ⁿ = 2⁵ = 32" },
      ],
    },
    {
      title: "Đề Thi Thử HSA - Toán Học 2025",
      type: "HSA",
      subject: "Toán",
      difficulty: "Trung bình",
      questionsCount: 40,
      durationMinutes: 50,
      attemptCount: 3210,
      isFree: false,
      year: 2025,
      description: "Đề thi thử phần Toán học trong kỳ thi HSA. Bao gồm các dạng bài tập đại số, giải tích và hình học.",
      questions: [
        { id: 1, text: "Tính tích phân ∫₀¹ (2x + 1)dx:", options: ["A. 1", "B. 2", "C. 3", "D. 4"], correctOptionIndex: 1, explanation: "∫(2x+1)dx = [x²+x]₀¹ = (1+1) - (0) = 2" },
        { id: 2, text: "Phương trình đường thẳng đi qua điểm A(1,2) và có hệ số góc k=3 là:", options: ["A. y = 3x - 1", "B. y = 3x + 1", "C. y = 3x + 2", "D. y = x + 3"], correctOptionIndex: 0, explanation: "y - 2 = 3(x - 1) → y = 3x - 1" },
      ],
    },
    {
      title: "Đề Thi Thử HSA - Ngữ Văn 2025",
      type: "HSA",
      subject: "Văn",
      difficulty: "Trung bình",
      questionsCount: 30,
      durationMinutes: 40,
      attemptCount: 2890,
      isFree: false,
      year: 2025,
      description: "Đề thi thử phần Ngữ văn và Khoa học xã hội trong kỳ thi HSA.",
      questions: [],
    },
    {
      title: "Đề Thi Thử HSA - Khoa Học Tự Nhiên",
      type: "HSA",
      subject: "Khoa học",
      difficulty: "Khó",
      questionsCount: 50,
      durationMinutes: 60,
      attemptCount: 1750,
      isFree: false,
      year: 2025,
      description: "Đề thi thử phần Khoa học tự nhiên (Vật lý, Hóa học, Sinh học) trong kỳ thi HSA.",
      questions: [],
    },
    {
      title: "Đề Thi Thử TSA - Toán Học Tư Duy",
      type: "TSA",
      subject: "Toán",
      difficulty: "Khó",
      questionsCount: 35,
      durationMinutes: 45,
      attemptCount: 2100,
      isFree: false,
      year: 2025,
      description: "Đề thi thử phần Toán tư duy trong kỳ thi TSA của Đại học Bách Khoa.",
      questions: [
        { id: 1, text: "Cho hàm số f(x) = |x² - 4|. Tập hợp điểm gián đoạn của f là:", options: ["A. {-2, 2}", "B. {}", "C. {0}", "D. {-2, 0, 2}"], correctOptionIndex: 1, explanation: "Hàm f(x) = |x² - 4| liên tục trên toàn bộ R, không có điểm gián đoạn." },
      ],
    },
    {
      title: "Đề Thi Thử TSA - Đọc Hiểu Học Thuật",
      type: "TSA",
      subject: "Đọc hiểu",
      difficulty: "Trung bình",
      questionsCount: 30,
      durationMinutes: 35,
      attemptCount: 1890,
      isFree: false,
      year: 2025,
      description: "Đề thi thử phần Đọc hiểu học thuật trong kỳ thi TSA.",
      questions: [],
    },
    {
      title: "HSA ĐHQGHN 2023 - Đề Chính Thức",
      type: "HSA",
      subject: "Tổng hợp",
      difficulty: "Khó",
      questionsCount: 120,
      durationMinutes: 150,
      attemptCount: 12300,
      isFree: true,
      year: 2023,
      description: "Đề thi HSA chính thức năm 2023 của ĐHQGHN.",
      questions: [],
    },
  ]);

  await db.insert(blogPostsTable).values([
    {
      title: "Lộ Trình Học HSA Hiệu Quả Trong 3 Tháng",
      category: "Học thuật",
      readingTimeMinutes: 8,
      thumbnail: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&q=80",
      publishedAt: new Date("2025-05-15"),
      excerpt: "Nếu bạn chỉ còn 3 tháng trước kỳ thi HSA, đây là lộ trình học tập được thiết kế khoa học để tối đa hóa điểm số của bạn.",
      content: `# Lộ Trình Học HSA Hiệu Quả Trong 3 Tháng\n\nKỳ thi HSA (Đánh giá năng lực ĐHQGHN) là một trong những kỳ thi quan trọng nhất với học sinh Việt Nam...\n\n## Tháng 1: Xây dựng nền tảng\n\nTrong tháng đầu tiên, hãy tập trung vào việc ôn tập toàn bộ kiến thức cơ bản...\n\n## Tháng 2: Luyện đề chuyên sâu\n\nSau khi đã nắm vững nền tảng, chuyển sang giai đoạn luyện đề tích cực...\n\n## Tháng 3: Mô phỏng thi thật\n\nTháng cuối cùng là lúc để bạn mô phỏng điều kiện thi thật nhất có thể...`,
      authorName: "Thầy Nguyễn Minh Tuấn",
      authorAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=NMT&backgroundColor=102A43&textColor=ffffff",
    },
    {
      title: "Phân Tích Cấu Trúc Đề Thi TSA 2024 Chi Tiết",
      category: "Phân tích đề thi",
      readingTimeMinutes: 12,
      thumbnail: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=600&q=80",
      publishedAt: new Date("2025-05-10"),
      excerpt: "Phân tích chi tiết cấu trúc đề thi TSA 2024 của Đại học Bách Khoa Hà Nội, bao gồm phân bổ điểm, mức độ khó và chiến lược làm bài.",
      content: `# Phân Tích Cấu Trúc Đề Thi TSA 2024\n\nĐề thi TSA 2024 của Đại học Bách Khoa Hà Nội có những điểm thay đổi đáng chú ý so với các năm trước...\n\n## Cấu trúc tổng thể\n\nĐề gồm 100 câu trong 90 phút, chia thành 3 phần chính...`,
      authorName: "Thầy Phạm Đức Hùng",
      authorAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=PDH&backgroundColor=102A43&textColor=ffffff",
    },
    {
      title: "10 Sai Lầm Thường Gặp Khi Luyện Thi HSA",
      category: "Kinh nghiệm",
      readingTimeMinutes: 6,
      thumbnail: "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=600&q=80",
      publishedAt: new Date("2025-05-05"),
      excerpt: "Những sai lầm phổ biến nhất mà học sinh mắc phải khi luyện thi HSA và cách khắc phục hiệu quả để cải thiện điểm số.",
      content: `# 10 Sai Lầm Thường Gặp Khi Luyện Thi HSA\n\nQua nhiều năm dạy học và tiếp xúc với hàng nghìn học sinh, thầy đã đúc kết ra những sai lầm phổ biến nhất...\n\n## Sai lầm 1: Học thuộc lòng thay vì hiểu bản chất\n\nĐây là sai lầm lớn nhất và phổ biến nhất...`,
      authorName: "Cô Trần Thị Lan Anh",
      authorAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=TLA&backgroundColor=E85A2A&textColor=ffffff",
    },
    {
      title: "So Sánh HSA và TSA: Nên Thi Kỳ Thi Nào?",
      category: "Tư vấn",
      readingTimeMinutes: 10,
      thumbnail: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&q=80",
      publishedAt: new Date("2025-04-28"),
      excerpt: "Phân tích điểm khác biệt giữa kỳ thi HSA và TSA để giúp học sinh chọn đúng hướng ôn thi phù hợp với mục tiêu đại học.",
      content: `# So Sánh HSA và TSA: Nên Thi Kỳ Thi Nào?\n\nCả HSA và TSA đều là những kỳ thi quan trọng, nhưng phục vụ cho những mục tiêu khác nhau...`,
      authorName: "Thầy Phạm Đức Hùng",
      authorAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=PDH&backgroundColor=102A43&textColor=ffffff",
    },
    {
      title: "Bí Quyết Nâng Điểm Đọc Hiểu TSA Từ 60 Lên 85",
      category: "Học thuật",
      readingTimeMinutes: 7,
      thumbnail: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&q=80",
      publishedAt: new Date("2025-04-20"),
      excerpt: "Chia sẻ phương pháp và chiến lược cụ thể giúp nhiều học sinh nâng điểm đọc hiểu TSA lên đáng kể chỉ trong 8 tuần.",
      content: `# Bí Quyết Nâng Điểm Đọc Hiểu TSA\n\nPhần đọc hiểu học thuật là một trong những phần khó nhất của kỳ thi TSA...`,
      authorName: "Cô Trần Thị Lan Anh",
      authorAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=TLA&backgroundColor=E85A2A&textColor=ffffff",
    },
  ]);

  await db.insert(testimonialsTable).values([
    {
      studentName: "Nguyễn Hoàng Nam",
      studentAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=NHN&backgroundColor=102A43&textColor=ffffff",
      score: 108,
      improvement: 30,
      testimonialText: "Sau 3 tháng học cùng TRI ANH EDU, điểm HSA của mình tăng từ 78 lên 108 điểm. Phương pháp học theo lộ trình cá nhân hóa thực sự hiệu quả. Mình đã đỗ vào ngành Công nghệ thông tin ĐHQGHN!",
      examType: "HSA",
      monthsStudied: 3,
    },
    {
      studentName: "Trần Minh Châu",
      studentAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=TMC&backgroundColor=E85A2A&textColor=ffffff",
      score: 95,
      improvement: 22,
      testimonialText: "Điểm TSA của mình từ 73 lên 95. Các bài giảng về tư duy toán học rất dễ hiểu và có nhiều ví dụ thực tế. Giờ mình tự tin làm bài trong 90 phút mà không bị áp lực thời gian.",
      examType: "TSA",
      monthsStudied: 4,
    },
    {
      studentName: "Lê Thị Thu Hà",
      studentAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=LTTH&backgroundColor=F7941D&textColor=ffffff",
      score: 112,
      improvement: 25,
      testimonialText: "Tính năng thi thử online giống hệt thi thật đã giúp mình quen với áp lực thi cử. Kết quả phân tích chi tiết sau mỗi lần thi cho mình biết chính xác cần cải thiện điều gì.",
      examType: "HSA",
      monthsStudied: 5,
    },
    {
      studentName: "Phạm Quốc Bảo",
      studentAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=PQB&backgroundColor=102A43&textColor=ffffff",
      score: 88,
      improvement: 18,
      testimonialText: "Kho đề thi với hàng trăm đề từ năm 2018-2024 là tài sản vô cùng quý giá. Mình đã luyện đủ các dạng bài nên không bị bất ngờ khi thi thật. Cảm ơn TRI ANH EDU!",
      examType: "TSA",
      monthsStudied: 3,
    },
    {
      studentName: "Vũ Thị Ngọc Ánh",
      studentAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=VTNA&backgroundColor=E85A2A&textColor=ffffff",
      score: 105,
      improvement: 28,
      testimonialText: "Thầy Tuấn dạy rất tận tâm, luôn giải đáp thắc mắc nhanh chóng. Chỉ số phân tích kết quả học tập giúp mình nhận ra mình yếu phần nào để tập trung ôn thi đúng hướng.",
      examType: "HSA",
      monthsStudied: 4,
    },
  ]);

  logger.info("Database seeded successfully");
}
